version: '3'

services:
  gateway:
    build:
      context: ./Gateway
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
